INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",1);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",2);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",3);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",4);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",5);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",6);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",7);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",8);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",9);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",10);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",11);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",12);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",13);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",14);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",15);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",16);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",17);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",18);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",19);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",20);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",21);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",22);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",23);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",24);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",25);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",26);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",27);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",28);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",29);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",30);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",31);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",32);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",33);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",34);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",35);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",36);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",37);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",38);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",39);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",40);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",41);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",42);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",43);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",44);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",45);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",46);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",47);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",48);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",49);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'unsolved' ",50);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",51);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",52);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",53);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",54);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",55);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",56);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",57);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",58);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",59);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",60);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",61);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",62);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",63);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",64);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",65);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",66);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",67);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",68);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",69);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",70);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",71);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",72);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",73);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",74);
INSERT INTO `question_status` (`status`,`question_id`) VALUES (" 'solved'",75);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",76);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",77);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",78);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",79);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",80);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",81);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",82);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",83);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",84);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",85);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",86);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",87);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",88);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",89);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",90);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",91);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",92);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",93);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",94);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",95);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",96);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",97);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",98);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",99);
INSERT INTO `question_status` (`status`,`question_id`) VALUES ("'expert' ",100);

